config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian), message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:index, :new, :create]

  def index
    @reviews = @restaurant.reviews
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@review.restaurant.id)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="container pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= link_to "Back to list", restaurants_path, class: "btn btn-primary mb-3" %>

<%= simple_form_for (@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <li style="list-style: none"><%= restaurant.name %> (<%= restaurant.category %>) <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary p-3" %></li>
  <br>
<% end %>

<%= link_to "Create new", new_restaurant_path, class: "btn btn-primary"%>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> (<%= @restaurant.category %>)</h1>

<br>

<%= link_to "See reviews", restaurant_reviews_path(@restaurant), class: "btn btn-primary" %>

<p>Adress: <%= @restaurant.address %></p>
<p>Phone Number: <%= @restaurant.phone_number %></p>

<br>
<br>

<%= link_to "Write review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>

<%= link_to "Back to list", restaurants_path, class: "btn btn-primary" %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews for <%= @restaurant.name %></h1>

<% @reviews.each do |review| %>
  <p>Description: <%= review.content %>></p>
  <p>Rating: <%= review.rating %></p>
<% end %>

<%= link_to "Back to Restaurant", restaurant_path(@restaurant), class: "btn btn-primary" %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>